import type { BotState } from "./types";

export const MOCK_BOTS: BotState[] = [
  {
    bot_id: "orbit",
    bot_name: "Orbit 1D Crypto Momentum",
    asset_class: "Crypto Spot",
    timeframe: "1d",
    status: "PAPER",
    updated_at: new Date().toISOString(),
    total_return_pct: 35.2,
    sharpe_ratio: 0.5,
    max_drawdown_pct: -18.9,
    win_rate_pct: 64.2,
    profit_factor: 1.34,
    trade_count: 153,
    current_position: null,
    equity_usdt: 13520,
    equity_curve: Array.from({ length: 40 }, (_, i) => ({
      timestamp: new Date(Date.now() - (39 - i) * 86400000).toISOString(),
      equity: 10000 * (1 + (0.352 * i) / 39),
    })),
    recent_trades: [],
    logs: [
      {
        time: new Date().toISOString(),
        level: "INFO",
        message: "Mock Orbit state — run paper bot to refresh orbit_state.json",
      },
    ],
    accepted: true,
    acceptance_note: "Walk-forward ACCEPTED (9/9 Gates Passed)",
    mock: true,
  },
  {
    bot_id: "gold",
    bot_name: "Gold 1H Volatility Breakout",
    asset_class: "XAU/USD",
    timeframe: "1h",
    status: "IDLE",
    updated_at: new Date().toISOString(),
    total_return_pct: 12.4,
    sharpe_ratio: 0.82,
    max_drawdown_pct: -9.1,
    win_rate_pct: 51.0,
    profit_factor: 1.28,
    trade_count: 48,
    current_position: null,
    equity_usdt: 112400,
    equity_curve: Array.from({ length: 40 }, (_, i) => ({
      timestamp: new Date(Date.now() - (39 - i) * 3600000).toISOString(),
      equity: 100000 * (1 + (0.124 * i) / 39),
    })),
    recent_trades: [],
    logs: [
      {
        time: new Date().toISOString(),
        level: "INFO",
        message: "Mock Gold state — run python -m gold_bot.engine",
      },
    ],
    mock: true,
  },
  {
    bot_id: "mnq",
    bot_name: "Nasdaq 15m ORB",
    asset_class: "MNQ Futures",
    timeframe: "15m",
    status: "IDLE",
    updated_at: new Date().toISOString(),
    total_return_pct: 8.7,
    sharpe_ratio: 0.61,
    max_drawdown_pct: -6.4,
    win_rate_pct: 47.5,
    profit_factor: 1.19,
    trade_count: 62,
    current_position: null,
    equity_usdt: 54350,
    equity_curve: Array.from({ length: 40 }, (_, i) => ({
      timestamp: new Date(Date.now() - (39 - i) * 900000).toISOString(),
      equity: 50000 * (1 + (0.087 * i) / 39),
    })),
    recent_trades: [],
    logs: [
      {
        time: new Date().toISOString(),
        level: "INFO",
        message: "Mock MNQ state — run python -m mnq_bot.engine",
      },
    ],
    mock: true,
  },
];
